name: My second Workflow
on: push
jobs:
    first_job:
         runs-on: ubuntu-latest
         steps:
            - name: Welcom message
              run: echo "hello world"
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Read file
              run: cat README.md