name: My second Workflow
on: push
jobs:
    first_job:
         runs-on: ubuntu-latest
         steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: List anf read files
              run: |
                cat README.md
                echo "hello world"
                ls -ltra
            - name: Generate ASCII artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON" >> dragon.txt